---
# The playbook uploads experiment artifacts to remote machines

- hosts: registry
  tasks:
    - name: killing registery
      shell: 
        cmd: pkill registery || /bin/true

    - name: Add or modify nofile soft limit for the user joe
      community.general.pam_limits:
        domain: root
        limit_type: soft
        limit_item: nofile
        value: 10000000

    - name: deploying registery service
      shell: cd ~/rapidchain; nohup ./registery > registery.log 2>&1 &


- hosts: all
  tasks:
    - name: killing nodes
      shell: 
        cmd: pkill node || /bin/true

    - name: deploying nodes
      shell: cd ~/rapidchain; ./deploy-nodes.sh 25 "{{ groups['registry'][0] }}:1234" eno1